rabbitmq.exchange.messages.name=exchange.message
rabbitmq.queue.messages.name=queue.message
rabbitmq.binding.messages.routing.key=message.routingKey
rabbitmq.queue.email.name=queue.email
rabbitmq.binding.email.routing.key=email.routingKey
rabbitmq.queue.sns.name=queue.sns
rabbitmq.binding.sns.routing.key=sns.routingKey